# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, verbose_name='订单号')),
                ('brand', models.CharField(max_length=8, verbose_name='品牌')),
                ('ctitle', models.CharField(max_length=50, verbose_name='车名')),
                ('orderStatus', models.IntegerField(choices=[(0, '未出价'), (1, '已出价'), (2, '订单关闭')], default=0, verbose_name='订单状态')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
        ),
    ]
