# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='消息')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('isRead', models.BooleanField(default=False, verbose_name='是否阅读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '消息列表',
                'verbose_name': '消息记录列表',
            },
        ),
    ]
