# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.IntegerField(choices=[(0, '未绑定'), (1, 'CBC'), (2, 'ABC'), (3, 'BC'), (4, 'ICBC')], default=0, verbose_name='银行'),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '激活')], default=0, verbose_name='角色'),
        ),
    ]
