# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190417_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_brand',
            field=models.ImageField(default='normal,png', upload_to='image/logo', verbose_name='标志'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='picture',
            field=models.ImageField(default='normal.png', upload_to='image/car', verbose_name='图片'),
        ),
    ]
