# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190417_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='mileage',
            field=models.IntegerField(verbose_name='公里数'),
        ),
    ]
