# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190417_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='extractprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='成交价格'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='newprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='新车价格'),
        ),
    ]
